bounswe/bounswe2017group2

- API Test App/ConcertAPI/concert/views.py
Added GET, POST, PUT and DELETE endpoints for User.
> Added endpoints for User

- API Test App/ConcertAPI/concert/tests.py
I added unit tests for;
- get concert by ID
- get all concerts
> Created Get Unit Tests for Concert

- API Test App/ConcertAPI/concert/tests.py
ı populated user DB and ımplemeted unit test for create user.
> added Create User unit test

- API Test App/ConcertAPI/concert/tests.py
Had to create this pull request again because of conflicts.
> New pull request for POST concert

- API Test App/ConcertAPI/concert/tests.py
I just implemented test case for user update? Could you check it?
> feature test update user implemented

- API Test App/ConcertAPI/concert/tests.py
Just made small changes in comments
> Rearranged and improved comments

- API Test App/README.md
> Get all users

- API Test App/ConcertAPI/ConcertAPI/settings.py
- API Test App/ConcertAPI/requirements.txt
- API Test App/ConcertAPI/settings.py
> changed requirements.txt and ALLOWED_HOSTS in settings.py in ConcertAPI

- API Test App/README.md
removed commas between parameters and spaces between argument = value
> fixed PUT requests

- LookingForConcerts/.idea/misc.xml
- LookingForConcerts/app/build.gradle
- LookingForConcerts/app/src/main/AndroidManifest.xml
- LookingForConcerts/app/src/main/java/com/swegroup2/lookingforconcerts/Concert.java
- LookingForConcerts/app/src/main/java/com/swegroup2/lookingforconcerts/ConcertDto.java
- LookingForConcerts/app/src/main/java/com/swegroup2/lookingforconcerts/ConcertListActivity.java
- LookingForConcerts/app/src/main/java/com/swegroup2/lookingforconcerts/ConcertListAdapter.java
- LookingForConcerts/app/src/main/java/com/swegroup2/lookingforconcerts/CreateConcertActivity.java
- LookingForConcerts/app/src/main/java/com/swegroup2/lookingforconcerts/LoginActivity.java
- LookingForConcerts/app/src/main/java/com/swegroup2/lookingforconcerts/RestInterfaceController.java
- LookingForConcerts/app/src/main/res/layout/activity_concert_list.xml
- LookingForConcerts/app/src/main/res/layout/activity_login.xml
- LookingForConcerts/app/src/main/res/layout/list_item.xml
- LookingForConcerts/app/src/main/res/values/strings.xml
Implemented login and list parts
> Implement login and list view

- Android/app/src/main/java/com/swegroup2/lookingforconcerts/RestInterfaceController.java
Added post url so that we don't forget to add it during implementation
> Add post url

- Android/app/src/main/java/com/swegroup2/lookingforconcerts/ConcertDto.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/CreateConcertActivity.java
Quick fix for the get request error.
> Fix get request error

- front-end/lfc-frontend/src/app/app.module.ts
- front-end/lfc-frontend/src/app/concert-detail.component.html
- front-end/lfc-frontend/src/app/concert-detail.component.ts
- front-end/lfc-frontend/src/app/create-concert.component.ts
- front-end/lfc-frontend/src/app/design.css
Concert detail page woth comment submitting.
No user authentication
> Created concert detail page

- Android/.idea/modules.xml
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/LoginActivity.java
> Implemented login feature for Android

- lfc-api/LookingForConcerts/LookingForConcerts/urls.py
- lfc-api/LookingForConcerts/lfc_backend/models.py
- lfc-api/LookingForConcerts/lfc_backend/serializers.py
- lfc-api/LookingForConcerts/lfc_backend/views.py
Implemented get user info.
Modified login.
> Implemented delete user (with authorization).

- Android/app/src/main/java/com/swegroup2/lookingforconcerts/ConcertDto.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/SignupActivity.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/UserDto.java
- Android/app/src/main/res/layout/activity_login.xml
- Android/app/src/main/res/layout/activity_signup.xml
Added signup functionality with username, email and password.
> Fixed signup funcitonality.

- .gitignore
- lfc-api/LookingForConcerts/LookingForConcerts/settings.py
- lfc-api/LookingForConcerts/LookingForConcerts/urls.py
- lfc-api/LookingForConcerts/lfc_backend/models.py
- lfc-api/LookingForConcerts/lfc_backend/views.py
- Commented urls.py extensively and changed some endpoints(!)
- Modified .gitignore, now ignoring .pyc and .sqlite3.
- Modified views.py, corrected 'GET' and 'POST' status of some views
> Implemented deactivate and delete user

- lfc-api/LookingForConcerts/LookingForConcerts/settings.py
- lfc-api/LookingForConcerts/LookingForConcerts/urls.py
- lfc-api/LookingForConcerts/lfc_backend/serializers.py
- lfc-api/LookingForConcerts/lfc_backend/views.py
We need to populate the docs.
I also made some modifications in settings.py for Spotify integration.
> Added Swagger for API Documentation

- Android/app/src/main/res/values/colors.xml
```<?xml version="1.0" encoding="utf-8"?>
<resources>
<color name="colorPrimary">#bf0303</color>
<color name="colorPrimaryDark">#8e0404</color>
<color name="colorAccent">#0a038e</color>
</resources>```
> Theme colors are changed

- Android/app/src/main/java/com/swegroup2/lookingforconcerts/ConcertListActivity.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/LoginActivity.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/RestInterfaceController.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/UserDto.java
- Android/app/src/main/res/layout/fragment_concert_details.xml
- Now, user does not have to enter username and password for every login. Token is registered to Shared Preferences.
- Also, UserDto is designed according to new changes on backend
fixes #168
> Login and logout are changed according to preferences

- front-end/lfc-react/src/components/pages/ConcertDetailPage.js
Added google maps to concert detail page.
> Google Maps

- front-end/lfc-react/src/App.js
- front-end/lfc-react/src/components/pages/ConcertDetailPage.js
- front-end/lfc-react/src/components/pages/ConcertDetailPage/ConcertDetailPage.js
- front-end/lfc-react/src/components/pages/ConcertDetailPage/design.css
Added comment box and follow buttons
Added design with css
> React front end concert detail comment follow

- .idea/bounswe2017group2.iml
- .idea/compiler.xml
- .idea/copyright/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- .idea/workspace.xml
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/ConcertListActivity.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/LoginActivity.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/RestInterfaceController.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/SignupActivity.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/UserDto.java
- Android/app/src/main/res/layout/activity_concert_list.xml
- Android/app/src/main/res/layout/activity_signup.xml
New fields are added to the signup page.
> Signup page is updated

- lfc-api/LookingForConcerts/lfc_backend/views.py
> Solved a Bug for Unfollowing User Endpoint

- lfc-api/LookingForConcerts/LookingForConcerts/urls.py
- lfc-api/LookingForConcerts/lfc_backend/views.py
Added an endpoint for getting subscribed concerts of an user.
Endpoint: user/\<pk\>/get_concerts/
Request Type: GET
> Get Subscribed Concerts of an User with User's Pk

- front-end/lfc-react/src/components/pages/ConcertDetailPage/ConcertDetailPage.js
- front-end/lfc-react/src/components/pages/ProfilePage/ProfilePage.js
Non registered users can now view concert and user profile pages.
There will be no "attend" or "follow" button or comment box.
> React front end nonuser

- front-end/lfc-react/src/components/pages/ProfilePage/ProfilePage.js
Fixed the followed concerts bug.
Can now see the viewed user's following concerts instead of logged in user's.
Prevented some possible, variable name confusion.
> React front end followed concerts

- front-end/lfc-react/src/components/pages/ProfilePage/ProfilePage.js
- front-end/lfc-react/src/components/pages/ProfilePage/design.css
Followers are show in a more beautiful way in profile page.
> Follower shown

- front-end/lfc-react/.gitignore
- front-end/lfc-react/package.json
- front-end/lfc-react/src/App.js
- front-end/lfc-react/src/actions/auth.js
- front-end/lfc-react/src/actions/concert.js
- front-end/lfc-react/src/actions/users.js
- front-end/lfc-react/src/api.js
- front-end/lfc-react/src/components/forms/LoginForm.js
- front-end/lfc-react/src/components/forms/SignupForm.js
- front-end/lfc-react/src/components/navigation/TopNavigation.js
- front-end/lfc-react/src/components/pages/DashboardPage.js
- front-end/lfc-react/src/components/pages/HomePage.js
- front-end/lfc-react/src/components/pages/LoginPage.js
- front-end/lfc-react/src/components/pages/SignupPage.js
- front-end/lfc-react/src/components/routes/UserRoute.js
- front-end/lfc-react/src/index.js
- front-end/lfc-react/src/localStorage.js
- front-end/lfc-react/src/reducers/concert.js
- front-end/lfc-react/src/rootReducer.js
- front-end/lfc-react/src/types.js
- front-end/lfc-react/src/utils/refreshToken.js
- front-end/lfc-react/yarn.lock
Changes:
-  Implemented functioning top navigation but search bar is dummy for now,
-  Implemented Main Page component that requests concerts from the API and lists them.
-  Fixed signup error handling bug.
-  Some other minor bug fixes.
> Front-end Top Navigation and Main Page

- front-end/lfc-react/src/App.js
- front-end/lfc-react/src/components/pages/ConcertDetailPage/ConcertDetailPage.js
- front-end/lfc-react/src/components/pages/DashboardPage.js
Concert detail and profile page
> Connected profile and concert detail page

- front-end/lfc-react/src/components/pages/ConcertDetailPage/ConcertDetailPage.js
- front-end/lfc-react/src/components/pages/ConcertDetailPage/design.css
- front-end/lfc-react/src/components/pages/ProfilePage/ProfilePage.js
- front-end/lfc-react/yarn.lock
Users can now rate attended concerts
> React front end concert rate

- front-end/lfc-react/src/App.js
- front-end/lfc-react/src/components/navigation/TopNavigation.js
- front-end/lfc-react/src/components/pages/ConcertDetailPage/ConcertDetailPage.js
- front-end/lfc-react/src/components/pages/LoginPage.js
- front-end/lfc-react/src/components/pages/ProfilePage/ProfilePage.js
Concert detail page's error is fixed, and "Profile" in top navigation is linked to logged in user's profile page.
> Fix: Authorization Error in the Concert-Detail Page

- front-end/lfc-react/src/components/pages/ConcertDetailPage/ConcertDetailPage.js
- front-end/lfc-react/src/components/pages/ConcertDetailPage/design.css
Non rated concerts dont give error anymore.
Average ratings of concerts are shown.
A button to buy ticket is shown in the corner of concert detail page.
Concert tags are shown in the concert detail page.
> React front end fix non rated concert bug

- Android/app/src/main/res/layout/activity_concert_list.xml
- Android/app/src/main/res/values/colors.xml
- Buttons are designed
- Colors are changed
> ConcertList Page is designed

- Android/app/src/main/java/com/swegroup2/lookingforconcerts/RestInterfaceController.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/ConcertListActivity.java
- Android/app/src/main/res/layout/activity_concert_list.xml
- Recommendations can be seen on the main page.
> Recommendation is implemented.

- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/ConcertDetails.java
- Android/app/src/main/res/layout/fragment_concert_details.xml
Users will be able to see the ticket link of the concert.
> Show seller url in concert details page

- Android/app/build.gradle
- Android/app/src/main/AndroidManifest.xml
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/RestInterfaceController.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/ConcertDetails.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/ConcertListActivity.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/CreateConcertActivity.java
- Android/app/src/main/res/layout/fragment_concert_details.xml
- Android/build.gradle
Users will now be able to see the location of a concert on a map
Also includes some bug fixes.
> Add google maps to concert detail page

- front-end/lfc-react/package.json
- front-end/lfc-react/src/App.js
- front-end/lfc-react/src/components/navigation/TopNavigation.js
- front-end/lfc-react/src/components/pages/ProfilePage/ProfilePage.js
- front-end/lfc-react/src/components/pages/ProfilePage/design.css
- front-end/lfc-react/yarn.lock
Spotify connection is done.
Now users can connect to spotify using a button in profile page.
Users can also disconnect from spotify.
/me is added. Profile button now links to /me
> Front end spotify connect

- lfc-api/LookingForConcerts/LookingForConcerts/settings.py
- lfc-api/LookingForConcerts/LookingForConcerts/urls.py
- lfc-api/LookingForConcerts/lfc_backend/views.py
Haluk and Enes, could you please double-check?
Thanks!
> Bug fixes, enhancements

- lfc-api/LookingForConcerts/LookingForConcerts/urls.py
- lfc-api/LookingForConcerts/lfc_backend/views.py
Our user is able to get recommended concerts from other users he/she follows.
> Recommendation by followed users implemented

- lfc-api/LookingForConcerts/LookingForConcerts/urls.py
- lfc-api/LookingForConcerts/lfc_backend/views.py
- concerts_annotations / -> list_annotations/
- concert/\<id\>/new_annotation/ -> new_annotation/
- annotation/\<id\>/ -> annotation/\<id\>/delete for DELETE
- annotations/ -> all_annotations/
> changed concert annotation and new_annotation endpoints' addresses

- lfc-api/LookingForConcerts/lfc_backend/views.py
At the request of the front-end, creating annotation can be done by everyone who installed lfc annotation widget on their computers.
> Create Annotation Accessible by Everyone

- lfc-api/LookingForConcerts/LookingForConcerts/settings.py
- lfc-api/LookingForConcerts/LookingForConcerts/urls.py
- lfc-api/LookingForConcerts/lfc_backend/models.py
- lfc-api/LookingForConcerts/lfc_backend/serializers.py
- lfc-api/LookingForConcerts/lfc_backend/views.py
Made some minor improvements/modifications in other files as well.
> Added Comment edit and delete. 

- Android/app/src/main/java/com/swegroup2/lookingforconcerts/RestInterfaceController.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/Artist.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/ConcertComment.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/ConcertDto.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/ConcertReport.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/user/UserDto.java
- Android/app/src/main/java/com/swegroup2/lookingforconcerts/user/UserReport.java
- User Reports object is created.
- Concert Report object is created.
-Object fields are fixed.
> User and Concert Report objects are added

- Android/app/src/main/java/com/swegroup2/lookingforconcerts/concert/ConcertDetails.java
- Android/app/src/main/res/layout/fragment_concert_details.xml
> add concert image to concert details

- front-end/lfc-react/src/App.js
- front-end/lfc-react/src/components/navigation/TopNavigation.js
EditProfile, CreateConcerts components ( the ones who need token ) now redirects to main page if guest user tries to reach.
> front-end redirect fixed

- front-end/lfc-react/src/components/navigation/TopNavigation.js
- front-end/lfc-react/src/components/pages/DashboardPage.js
Basic search is implemented and working fine.
> Front-end Basic Search

- lfc-api/LookingForConcerts/lfc_backend/tests/test_recommendation.py
Created 5 unittests for recommendation system.
> Recommendation Unittest
